Bambrp
ONSdigital/eq-address-lookup-api pull request #7
Opened 2019-04-17 12:40 UTC by bambrp

## Context?
We have a requirement for a proxy layer to serve up possible postal addresses from postcode or partial text matches from a lookup service.

This service was designed to test a specific internal provider, that was only available if we connected to it via VPC peering on the Google Cloud Platform, which necessitated the creation of kubernetes deployment scripts.

There was also a need to update the API calls to the latest version, and to restrict the number of address suggestions returned to a more reasonable 10 (down from 100).

## Reviewing
The onward service this proxy was created to talk to is hosted on a GCP project that you must enable VPC sharing with.

Additionally, since that service had no auth of its own, the proxy was responsible for securing it- this is done through GCP's Cloud Armor applying a set of firewall rules (a policy called _ons-only_) to restrict to a set of known IP addresses. You will need to implement this policy to make this deployable, or remove the rule in the BackendConfig section of _k8s/helm/templates/service.yaml_

Deployment is by running `k8s/deploy_app.sh LOOKUP_API_URL DOCKER_REGISTRY IMAGE_TAG` from the top level folder.

2019-05-09 10:23 UTC, JamesGardiner requested changes
Some minor formatting suggestions

2019-05-09 10:23 UTC, JamesGardiner commented on app/request_address.py
> +    """
Runner uses single quoted strings - we should maintain consistency across apps to make tooling simpler

2019-05-09 10:23 UTC, JamesGardiner commented on app/request_address.py
> +            (settings.LOOKUP_URL, 'addresses', 'partial?input=' + search_value + '&limit=' + settings.RESULT_LIMIT))
Could you break this up over multiple line to make it more readable?

2019-05-09 10:23 UTC, JamesGardiner commented on app/request_address.py
> +        raise Exception("ERROR IN ADDRESS INDEX API (try refresh). Reason: {}. Response: {}".format(resp.reason,
This should be an f-string

2019-05-09 11:44 UTC, bambrp commented on app/request_address.py
> +    """
I altered this as it's recommended by PEP257 that says docstrings should always be triple double-quoted. I have no horse in that race, will change if you want.

2019-05-09 11:57 UTC, bambrp commented on app/request_address.py
> +            (settings.LOOKUP_URL, 'addresses', 'partial?input=' + search_value + '&limit=' + settings.RESULT_LIMIT))
What's the current agreed line length with you guys? PEP8's 79 chars, a bit more?

2019-05-09 11:58 UTC, JamesGardiner commented on app/request_address.py
> +            (settings.LOOKUP_URL, 'addresses', 'partial?input=' + search_value + '&limit=' + settings.RESULT_LIMIT))
If we go down the Black formatting route (which we are in Runner), then 88

2019-05-09 11:59 UTC, bambrp commented on app/request_address.py
> +        raise Exception("ERROR IN ADDRESS INDEX API (try refresh). Reason: {}. Response: {}".format(resp.reason,
I tried to leave as much alone as I could and have it work, and only fixed things the PyCharm linter was moaning about. You want all strings of this ilk converting? i.e. template strings with variables to expand into them

2019-05-09 12:00 UTC, JamesGardiner commented on app/request_address.py
> +        raise Exception("ERROR IN ADDRESS INDEX API (try refresh). Reason: {}. Response: {}".format(resp.reason,
Ok, if we are being light touch then it seems fair to leave it as is, and make a wholesale change to f-strings in future (should we decide to in this project)

2019-05-09 13:05 UTC, bambrp commented on app/request_address.py
> +            (settings.LOOKUP_URL, 'addresses', 'partial?input=' + search_value + '&limit=' + settings.RESULT_LIMIT))
88, got it.

2019-05-14 08:59 UTC, JamesGardiner approved these changes

2019-06-20 09:55 UTC, JamesGardiner commented
@bambrp @pricem14pc can this be closed?

2019-06-20 15:12 UTC, closed without merging

2019-06-20 15:12 UTC, pricem14pc commented
This can be re-visited when the AI requirement resurfaces.